### ISSUE TITLE
rosstate: auto reconnect

### ISSUE THREAD

**Issue by VictorLamoine** [gavanderhoorn/fanuc_driver_exp#17] opened 2019-04-23 07:38 UTC
We have some networking issues and sometimes the connection with the robot is lost.

I want to record the robot joint values along with other sensors using ROS over a long period of time (> 1 hour). Currently this does not work because when a disconnect happens the connection is not established again, meaning after the first disconnect we won't get data from the robot anymore.

Note I am not controlling the robot (only `rosstate`, no `rostraj`) so it should be safe to auto-reconnect.

Is there a way to force both ends to auto reconnect?

**Comment by gavanderhoorn** [comment] 2019-04-23 09:00
Yes, so because of the way Karel sockets work, disconnecting sockets are actually not that easy to handle.

Can you show some wireshark traffic when the disconnect happens?

I have some concept-code (Karel) that can be used to detect connection drops, but I want to make sure that the problem is not on the `industrial_robot_client` side first.

**Comment by drchrislewis** [comment] 2019-04-29 14:06
@VictorLamoine @gavanderhoorn  We are having a very similar issue. We have long programs running where we need to actively monitor for collisions. Connection is lost, and we continue to operate without collision detection, or else we can rarely finish a program. Does anyone know why the connection is so fragile? We are on a local network, with little traffic. I will attempt to run wireshark today.

**Comment by gavanderhoorn** [comment] 2019-04-29 14:15
At the moment it's unclear.

I'm waiting for network traces from @VictorLamoine to know more.

**Comment by VictorLamoine** [comment] 2019-04-29 14:36
I won't do network traces before a long time because it is not a priority for us at the moment. (we fetch the robot pose with modbus registers and that's enough for us at the moment).

**Comment by gavanderhoorn** [comment] 2019-04-29 14:40
Without a trace it's going to be difficult for me to do anything, so if you want this looked at @drchrislewis you'll have to provide one.

Or use modbus as @VictorLamoine writes.

**Comment by drchrislewis** [comment] 2019-05-03 16:03
@VictorLamoine @gavanderhoorn  I did not obtain any wireshark recordings of this dropped connection issue. I removed one of the two netgear hubs between my computer and the controller and never experienced connection drops again.

**Comment by gavanderhoorn** [comment] 2019-05-04 10:36
Without a trace (to start with) this is going to be difficult to diagnose.

As both of you are apparently no longer affected by this / care about it, I'm going to close the issue.

**Closed as completed by gavanderhoorn** 2019-05-04 10:36 UTC
Labels: enhancement, more info needed
